### ISSUE TITLE
Format Document With Empties the source file

### ISSUE THREAD

**Issue by PaulMcInnis** [rmcmk/forge-format-vsc#1]
Running this empties my source with no issues in console. 

1. create a new file with this inside

        // SPDX-License-Identifier: MIT
        // compiler version must be greater than or equal to 0.8.20 and less than 0.9.0
        pragma solidity ^0.8.20;
        
        contract HelloWorld {
            string public greet = "Hello World!";
        }

2. command palette -> format with -> forge _(this extension)_
3. witness that lines are removed from the file, or the file is completely emptied
4. revert the file contents to step 1
5.  run from cli `forge fmt hello.sol` and witness that it works as expected

seems like there is some kind of issue with this extension?

**Comment by rmcmk** [comment]
@PaulMcInnis Hey, appreciate you raising the issue. Could you provide some details for me?

- Your Foundry formatter configuration
- The Foundry version (the tag is pinned at 0.2, please verify the date; if uncertain, run `foundryup` again to fetch the latest nightly)
- The version of forge-format-vsc
- Your VSCode version
- A complete list of extensions enabled in your workspace

Unfortunately, I couldn't reproduce the issue in my environment (using the latest extension, VSCode, and Foundry, with my configurations, etc.).

**Comment by PaulMcInnis** [comment]
hmm I'll chalk this one up to something on my end, I am able to format with the juanblanco extension just fine.

If I find some time to dig here i'll re-open
